# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2014

# 右クリックでターゲッティングしているときの、ターゲット取得最大距離
# 大きくすると、遠いプレイヤーも取得される。最大でも100以下にすること。
targetingRange: 40

# 右クリックでターゲッティングしているときの、ターゲット取得範囲(横方向)
# 大きくすると、ターゲットから離れたプレイヤーもターゲッティングされる。
targetingWidth: 2.5

# 同時にターゲット可能な対象数
maxTargetNum: 5

# ミサイルの加速スピード
missileAccelSpeed: 0.4

# ミサイルの最大スピード
missileMaxSpeed: 2.0

# 弾がヒットしたときに発生する爆風の強さ。
explosionPower: 3

# 弾がヒットしたときに対象に与える基本ダメージ量。
# 基本ダメージ量＋爆発によるダメージ量＝被弾した時の実際のダメージ量
explosionDamage: 3.0

# ミサイルランチャーとして使用するアイテムの素材
launcherMaterial: 'GOLD_HOE'

# 無限ミサイルモード
# true :  ミサイルが手持ちに無くても、ランチャーのみでミサイルを無限に発射できます。
#         PVPサーバー向け。
# false : 手持ちにミサイル（普通のエンダーパール）が必要です。
#         1発打つごとにエンダーパールを1個消費します。サバイバルサーバー向け。
infiniteMissileMode: true

# MOBへのターゲッティング有効無効を切り替えする
targetingToMob: true

# プレイヤーへのターゲッティング有効無効を切り替えする
targetingToPlayer: true
