name: ${project.name}
main: ${project.groupId}.${plugin.command.name}.${project.name}
version: ${project.version}
author: ucchy
description: ${project.description}
commands:
  ${plugin.command.name}:
    description: The command for ${project.name}.
    aliases: ${plugin.id.aliase}
    usage: |
           /<command> get - get new stinger missile.
           /<command> give (player) - give new stinger missile.
           /<command> reload - reload configuration file.
    permission: ${plugin.command.name}.command
    permission-message: You don't have "<permission>" permission.
permissions:
  ${plugin.command.name}.command:
    description: ${project.name} command permission.
    default: true
  ${plugin.command.name}.reload:
    description: ${project.name} reload command permission.
    default: op
  ${plugin.command.name}.get:
    description: ${project.name} get command permission.
    default: op
  ${plugin.command.name}.give:
    description: ${project.name} give command permission.
    default: op
  ${plugin.command.name}.action:
    description: ${project.name} action permission.
    default: true
  ${plugin.command.name}.*:
    children:
      ${plugin.command.name}.command: true
      ${plugin.command.name}.reload: true
      ${plugin.command.name}.get: true
      ${plugin.command.name}.give: true
      ${plugin.command.name}.action: true
    description: All of ${project.name} permission.
